elysiajs/elysia

src/index.ts
src/ws/types.ts

One of the clients in my project tries to open a websocket connection with the content type set to "application/json", but without sending a request body. This results in an error in the compiled handler (line 71 in compose.ts), so in order to fix this, I would need support for the "parse" lifecycle event also for websockets.
The other solution would be to do a more fine-grained handling of errors in the generated code in compose.ts, but for now I like the simplicity of the approach with only one try-catch block for everything.

Add support for "parse" lifecycle event for websockets.

---

src/index.ts
test/group.test.ts

Hi!
As i already mentioned this on Discord, groups do not work correctly with the new plugin model introduced in 0.6, this fixes that issue.
There is still an issue with the inferred type when we use a plugin prefix, but hopefully we can fix that too in the near future.

fix: groups with prefixed instance

---

src/types.ts

Closes #107 
It seems that the instance's errors were just not being passed to "ErrorHandle" on LocalHook

fix: pass instance errors typings to local error hook

---

src/index.ts
test/path.test.ts

Hi!
This PR introduces a significant feature enhancement to Elysia—support for passing an array of routes to a single handler. This enables cleaner, more efficient routing code by allowing one handler function to manage multiple routes.
- Updated `.get()`, `.post`, `.put()`, `.patch()`, `.delete()`, `.options()`, `.all()`, `.head()`, `.trace()`, `.connect()`, `.ws()`, and `.route()` to support passing either a singular string route, or an array of string routes.
- Extensive testing for each method, included in `path.test.ts`
```ts
import { Elysia, t } from 'elysia'
new Elysia()
.get(['/', '/index', '/index.html'], () => 'Hello index!')
```
[Credit to deadlinecode in the ElysiaJS Discord](https://discord.com/channels/1044804142461362206/1123557035963863040)

🎉 feat: route arrays

---

src/index.ts

Hi!
Just a couple changes, while working on route arrays I found some mismatching comments (comments for some functions were just duplicates of another function)
_No functional changes._

🔧 fix: comment typos

---

test/core/modules.test.ts

replace `describe` with `it` because of this
```
test/core/modules.test.ts:
134 | 
135 |           const app = new Elysia().use(a()).compile()
136 | 
137 |           await app.modules
138 | 
139 |           expect(app.routes.length).toBe(1)
^
TestNotRunningError: expect() must be called in a test
```

fix: modules test

---

src/index.ts
src/ws/index.ts
test/ws/message.test.ts
test/ws/utils.ts

#247
The issue is caused by the library always assuming that the message is `string`, or it will be stringified.
When the client sends a binary frame, the library always `JSON.stringify` the message including the `Buffer` object. 
This PR is change the codes so that,
- On `parseMessage`, if the message is not `string`, it will skip parsing as either `JSON` string or `Number`
- On `send` method, if the message is in `Buffer` format, it will transmit as-is and not `JSON.stringify` as it did before.
Also, this PR adds a test to target this issue.
PS: On testing, I've found that `should respond with remoteAddress` always returns false due to the difference in the format of the remote address. So I've added that kind of address format so the test can be passed.

fix: WS: Correct handling of Buffer object

---

src/cookie.ts
test/cookie/explicit.test.ts
test/cookie/implicit.test.ts
test/cookie/response.test.ts

When deleting a cookie, you need to match all attributes (path, domain, secure, sameSite) too, else you might run into issues with removing a cookie.
For example Firefox does not immaterially delete the cookie, if `path` is set on creation, but not on delete.
Since I thought the implementation for this is rather straight forward I didn't start a discussion about it. Let me know if something is wrong and I'll update it :)
This PR is related to #255 but that issue is more about `@elysiajs/cookie`.

feat: add `cookie.remove` options

---

src/utils.ts

When I define a typebox object with `$id` at `Elysia.model` and I use `t.Ref` in hooks then it will throw the error `Unable to dereference schema with $id 'undefined'` when starting the server.
This PR will add model references to TypeCompiler.Compile to fix this issue.
Error example:
```
new Elysia()
.model({
user: t.Object(
{
id: t.Number()
},
{
$id: "user"
}
)
})
.get(
"/",
() => ({
success: true,
data: {
id: 1
}
}),
{
response: {
200: t.Object({
success: t.Boolean(),
data: t.Ref("user")
})
}
}
)
.listen(3000)
```

Fix Unable to dereference schema with  'undefined' when using t.Ref

---

src/index.ts

I haven't encountered any issues with the previous code. However, in the group feature section, there is a sandbox instance that creates a new Elysia instance with the configuration of the previous instance. The group operates somewhat like a guard, so the guard should create a sandbox instance in a same way of group.
This seems to relate to #323.

fix: guard sandbox did not inherit global config.

---

src/index.ts
src/utils.ts
test/core/mount.test.ts

Query parameters weren't preserved for a mounted handler. This was because the new request url passed to the handler was assembled using only the hostname and path.
This fixes  #329

fix: preserve query params for mounted handler

---

src/index.ts

I need it to make a generic schema in Deno and can't import from `esm.sh/@sinclair/typebox` because it isn't compatible with the types from `esm.sh/elysia` (they use unique symbols internally)

reexport TSchema from typebox

---

src/index.ts

There was code to display this message but it didn't get hit because a second check which wasn't written correctly errors out first.
```diff
- ReferenceError: Bun is not defined
+ Error: .listen() is designed to run on Bun only. If you are running Elysia in other environment please use a dedicated plugin or export the handler via Elysia.fetch
```
Tested manually in Node. Attempted to test in Deno but their `--unstable-byonm` flag didn't seem to work, though it is possible to load the library through npm.

fix: display the correct error message when calling .listen outside of bun

---

example/websocket.ts
src/ws/index.ts

This is to address this issue #381
When `open` and `close` functions are run, the passed `ElysiaWS` objects are different. This is due to the fact that each time `open`/`close` is run they recreate the `ElysiaWS` object which recreates the ID:
And here's the offending code `src/index.ts:3234` and `src/index.ts:3264`:
The fix I came to that doesn't break anything really is to use a getter/setter for the `id` prop on `ElysiaWS` class and storing the id in the raw bunjs/uWebSocket socket (`ElysiaWS.raw`).
You'll probably notice that I used `randomInt()` instead of `Date.now()`. This is because if you run `Date.now()`/`performance.now()` you'll notice that there are duplicates. Of course `performance.now()` has less duplicates but still for a simple test with only 100 iterations the best I …

Fix: Websocket ID not the same for `open` and `close` functions

---

src/handler.ts
test/response/custom-response.test.ts
test/units/map-compact-response.test.ts
test/units/map-response.test.ts

Fixes: #421 
Related: #422 
@saltyaom Thanks for applying #422 , however there was a small bug where the response is still empty when set.headers is empty. This PR applies the fix for that.

fix(handler.ts): empty body custom response when set.headers is empty

---

test/core/scoped.test.ts

This merge request adds a test to cover the issue mentioned in #397.
Below is the test. It was inspired from @rimelke who commented on the issue.
``` ts
it('multible scoped events', async () => {
const first = new Elysia({ name: "first", scoped: true }).get("/first", () => "first");
const second = new Elysia({name: "second", scoped: true }).get("/second", () => "second");
const app = new Elysia().use(first).use(second);
const firstResponse = await app.handle(req("/first"));
const secondResponse = await app.handle(req("/second"));
const firstText = await firstResponse.text();
const secondText = await secondResponse.text();
expect(firstText).toBe("first")
expect(secondText).toBe("second")
})
```
Note i also removed a dublicate test found at …

Add test for #issue397

---

example/http.ts
src/index.ts
test/scoped/scoped.test.ts

- scoped plugin instances now respect the prefix property. 
- adding a second scoped plugin does not unmount the route handler of a previously added scoped instance anymore. 
In order for this to function a prefix has to be used. 
All tests as welll as my new test are passing. I didn't do perform manual tests for functionalities like `guard` which also was bugged.
````typescript
const app = new Elysia();
const plugin = new Elysia({
prefix: "Plugin",
scoped: true,
}).get("/testPrivate", () => "OK");
const plugin2 = new Elysia({
prefix: "PluginNext",
scoped: true,
}).get("/testPrivate", () => "OK");
app.use(plugin).use(plugin2);
const res = await app.handle(req("/Plugin/testPrivate"));
expect(res.status).toBe(200);
const res1 = await app.handle(req("/PluginNext/testPrivate")); …
```

fixes elysiajs/elysia#458 , fixes elysiajs/elysia/#457

---

src/compose.ts
test/validator/query.test.ts

Fixes #461 
Fixed a bug in parsing queries that have a hyphen or a dot in its key. The bug was in creating `c.query` in fnLiteral variable in composeHandler function. Fixed by adding single quotes around `${name}` when creating `c.query`.
Also added unit tests for both cases.
First time contributing so feedback is appreciated!

fix: Using a query key that contains a hyphen or a dot raises a SyntaxError

---

src/utils.ts
test/units/numeric.test.ts

this fixes #473
in https://github.com/elysiajs/elysia/blob/6fd8753fa2cf45f34a2af7f63a49659a987a87f7/src/utils.ts#L586
added extra checks to  return false if `message.length > 16`
or
double check the string if  `message.length = 16` by converting to string and comparing to message
if less then 16 then do normal checking
```ts
if (message.length < 16)
return message.trim().length !== 0 && !Number.isNaN(Number(message))
```
```ts
// if 16 digit but less then 9,007,199,254,740,991 then can be parsed
if (message.length === 16) {
const numVal = Number(message)
if (numVal.toString() === message)
return message.trim().length !== 0 && !Number.isNaN(numVal)
}
```

fix: Numeric Cookie with length >= 16 cant be parsed to number

---

src/index.ts
test/path/plugin.test.ts
test/plugins/errorPropagation.test.ts

expose nested scoped plugin routes in app.routes  fixes: elysiajs/elysia#470
run parent error handler if plugin onError completes without handling  fixes: elysiajs/elysia#469
The following code snippet seems to work fine and I didn't notice any regressions. Using the below code global error handlers are now executed as expected, but I did not test other handlers like `onRequest onBeforeHandle, ...` which probably should also be forwarded?  What would be the correct way to fix this?
````
plugin.event.error.push(...this.event.error);
````
Swagger is now working with nested plugins and our tests also seem to pass.

Fix #470 & #469

---

src/index.ts

The `transform` callback type signature for derive did not allow it to return a promise. This PR fixes that.

Fix callback return types for derive

---

src/index.ts
src/utils.ts

If we don't await the `promisedModules` (previously known as `lazyLoadModules`) within the `Elysia#_use` method, we will erroneously call `Elysia#compile` *before* all nested plugins have loaded.
This PR also introduces a new internal primitive called `PromiseGroup`. We don't want to keep all the plugin promises in memory forever, so that we can await the plugin promises within `Elysia#_use` and call `_use` again afterwards without fearing an endless loop. The `PromiseGroup` ensures no endless loop can occur.

fix: await the `.modules` of nested Elysia instances

---

src/index.ts

The following use case was broken: Calling `app.use(import("./routes"))` where the "./routes" module has a default export that is an Elysia instance.
I‘m doing `instanceof Elysia` checks on the promise result and the module‘s "default" export, so a more informative error can be thrown, where before the app would crash with some obscure TypeError with a message of "Right side of assignment cannot be destructured" within the `Elysia#_use` method.

fix: support for module promise in `Elysia#use`

---

src/index.ts

It's useful for plugins that delegate the scope to the users to being able to use the type directly like
```typescript
import { LifeCycleType } from 'elysia';
export interface PluginOptions {
as?: LifeCycleType;
// more options
}

export LifeCycleType so plugins can offer scope as an option

---

src/handler.ts

Fixing error return that cause server stop when the HTTP TEXT Stream is closed by the client before the server close it.
Initial Error:
```
1134 |         request?.signal.addEventListener(
1135 |           "abort",
1136 |           {
1137 |             handleEvent() {
1138 |               ;
1139 |               response.cancel(request);
^
TypeError: ReadableStream is locked
at cancel (:1:21)
at handleEvent (/root/Projects/dark-utilities/backend-api/node_modules/elysia/dist/index.mjs:1139:15)
```
How to reproduce ?
```ts
app.post('/api/v1/device/:id/shell', async ({ jwt, set, headers, request }) => {
return new Stream(async (controller) => {
setTimeout(() => {
controller.send('Hello, World!');
// client closed the connection at 5000ms before the server could complete the response …
```

Fixing "ReadableStream is locked"

---

src/utils.ts

This fixes a bug introduced in #549 where a rejected promise wouldn't be removed from its `PromiseGroup` instance.

fix: shift promise in `PromiseGroup` even when rejected

---

src/types.ts
test/types/index.ts

Allows success responses to derive their schema/type from non-200 status codes.
Fix https://github.com/elysiajs/elysia/issues/592

Fix: account for non-200 response schemas

---

src/utils.ts
test/core/normalize.test.ts

Fixes https://github.com/elysiajs/elysia/issues/631 by adjusting the behavior for normalization with additional properties settings to a more expectable way. Uses sensible defaults.

🐞 fix: set correct normalization behavior for addtional properties

---

src/cookies.ts

For example, if my cookie is 
```  
"cookie": "access-currency-info=%7B%22accessLangList%22%3A%5B%7B%22id%22%3A144%2C%22theDefault%22%3Atrue%2C%22accessLangCode%22%3A%22en-US%22%2C%22accessLangName%22%3A%22English%22%7D%2C%7B%22id%22%3A144%2C%22theDefault%22%3Afalse%2C%22accessLangCode%22%3A%22zh-CN%22%2C%22accessLangName%22%3A%22%u7B80%u4F53%u4E2D%u6587%22%7D%5D%2C%22currencyList%22%3A%5B%7B%22id%22%3A144%2C%22theDefault%22%3Atrue%2C%22currencyCode%22%3A%22MYR%22%2C%22currencyName%22%3A%22%u6797%u5409%u7279%22%2C%22currencySymbol%22%3A%22RM%22%2C%22symbolPosition%22%3A%22L%22%7D%5D%2C%22receiptCountryList%22%3A%5B%7B%22id%22%3A144%2C%22theDefault%22%3Atrue%2C%22receiptCountryCode%22%3A%22143749%22%2C%22receiptCountryName%22%3A%22Malaysia%22%7D%5D%2C%22lang%22%3A%22en-US%22%2C%22accessLang …
```

fix: cookie decode value might be null

---

package.json
src/index.ts
src/utils.ts
test/type-system/import.ts

Closes https://github.com/elysiajs/elysia/issues/723
---
- lazy instantiation of `stringToStructureCoercions` fixed it
- I added a new `script` to test standalone import. it doesn't work with `bun test` because `elysia/index.ts` is loaded before `elysia/type-system.ts`

fix: type-system standalone import

---

package.json

When I was using elysia and went into its `package.json` thanks to [`vscode-publint`](https://github.com/kravetsone/vscode-publint), I saw errors in the package configuration:
```bash
PS Z:\PROJECTS\forks\elysia> bunx publint
elysia lint results:
Suggestions:
1. The package does not specify the type field. Environments may incorrectly identify a CJS file as ESM in the future. Consider adding "type": "commonjs".
Warnings:
1. pkg.exports["."].types types is interpreted as CJS when resolving with the "import" condition. This causes the types to be ambiguous when default importing the package due to its implied interop. Consider splitting out two "types" conditions for "import" and "require", and use the .mts extension, e.g. pkg.exports["."].import.types: "./dist/index.d.mts"   
2. …
```

Fix package issues

---

src/types.ts

Exclude from OpenAPI/swagger file routes with inspired by [@fastify/swagger hide paths](https://github.com/fastify/fastify-swagger?tab=readme-ov-file#hide-a-route)
```ts
detail: {
hide: true
}
```
example
```ts
const app = new Elysia()
.use(swagger())
.get("/public", "omg")
.guard({
detail: {
hide: true
}
})
.get("/hidden", "ok")
```
Should be merged with https://github.com/elysiajs/elysia-swagger/pull/137
Close/helps https://github.com/elysiajs/elysia/issues/412

feat: add `hide` props in `detail` types for hide route from OpenAPI/swagger document

---

src/type-system.ts
test/type-system/union-enum.test.ts

```ts
it('JSON schema', () => {
expect(t.UnionEnum(['some', 'data'])).toMatchObject({
type: 'string',
enum: ['some', 'data']
})
expect(t.UnionEnum(['some', 1]).type).toBeUndefined()
expect(t.UnionEnum([2, 1])).toMatchObject({
type: 'number',
enum: [2, 1]
})
expect(t.UnionEnum([null])).toMatchObject({
type: 'null',
enum: [null]
})
})
```
Related - https://github.com/elysiajs/elysia/issues/512
JSON Schem 7 spec - https://json-schema.org/draft/2020-12/json-schema-validation#section-6.1.2
Docs - https://json-schema.org/understanding-json-schema/reference/enum

🎉: feat: add `UnionEnum` type with JSON schema enum usage

---

src/index.ts
test/core/stop.test.ts

This fixes #806, by adding support for Bun server's native `closeActiveConnections?: boolean` option on `server.stop()`. 
```ts
const app = new Elysia()
.get("/", () => 'hi')
.listen(3000)
// The boolean argument here is optional, new, and mimics native bun.
app.stop(true) // Abruptly any requests inflight
```

Add `closeActiveConnections` to server.stop(), like exists in native bun

---

src/compose.ts
test/core/compose.test.ts

This PR fixes a TypeError in `hasAdditionalProperties` when handling intersection types that include a TypeBox Record. The function fails when processing schemas that have `type: "object"` but no `properties` key.
When using an intersection (`Type.Intersect`) with a Record type from TypeBox, the generated schema is a valid JSON Schema object using `allOf`, but lacks a `properties` key in some of its subschemas. This causes `hasAdditionalProperties` to throw a TypeError when attempting to access the `properties` field.
Example schema that triggers the bug:
```json
{
"allOf": [
{
"type": "object",
"properties": {
"a": {
"type": "string"
}
},
"required": ["a"]
},
{
"type": "object",
"patternProperties": {
"^(0|[1-9][0-9]*)$": {
"type": "string"
}
}
}
]
}
```
Added test case for intersection …

fix: typebox object schemas without properties key

---

src/compose.ts
src/dynamic-handle.ts
test/core/handle-error.test.ts

Errors thrown in transform decoding would not get picked up by `app.handleError` because Typobox wraps them in a `TransformDecodeError`.
This proposal unwraps the error, allowing e.g. `NotFoundError` thrown in transform decoding to result in HTTP 404.
Fixes #882

fix: unwrap transform errors

---

src/type-system.ts
test/type-system/boolean-string.test.ts

The BooleanString converted value is a string instead of a boolean. This occurs because Typebox converts the value to the first matching schema, as shown here:
```typescript
function FromUnion(schema: TUnion, references: TSchema[], value: any): unknown {
for (const subschema of schema.anyOf) {
const converted = Visit(subschema, references, value)
if (!Check(subschema, references, converted)) continue
return converted
}
return value
}
```

fix: boolean-string converted to string

---

src/dynamic-handle.ts
test/lifecycle/resolve.test.ts

Fixes #888
@SaltyAom — it seems a little inconsistent to sprinkle cases with `{ aot: false }` over the tests. Perhaps you have a more exhaustive approach for full test coverage both with and without AOT?

:wrench: fix: handle `error()` in resolve with `aot: false`

---

src/type-system.ts
test/validator/query.test.ts

Possible fix for #872:
Using the following schema, the query string `?other=foo` is rejected with _422 expected boolean_.
```ts
t.Object({
registered: t.Optional(t.Boolean()),
other: t.String(),
})
```
The validation error is thrown in `BooleanString.Decode`.
@bogeychan please correct me if I'm wrong — I assume the intention in `Decode` is to check if `value` is present, not `property`?

Optional `BooleanString` decoding issue

---

src/type-system.ts
test/type-system/date.test.ts

Currently we hardcode the default for the `t.String` with date and date-time formats to the current time. We should be respecting the defaults that are being provided as part of the DateOptions.
In this PR, we use the default passed in via DateOptions to set the defaults for `t.String` with date and date-time formats, as well as `t.Number`.
I've added a test case in the first commit to demonstrate the bug I'm describing

fix: Correctly set `t.Date()` defaults

---

src/type-system.ts
test/validator/body.test.ts
test/validator/params.test.ts

Fixes #1011 
Tightens the schema used for Elysia's custom `t.Integer()` to reject numbers with any decimal content.
If there's some other considerations I'm missing feel free to let me know.

fix: replace t.Number() for Type.Integer()

---

src/index.ts
src/types.ts
src/utils.ts
test/extends/models.test.ts
test/types/index.ts

Hi 👋 
This is an initial attempt to address issues #402 and #921.
Changes Introduced:
- Array Type Aliases: Appended `[]` to the body and response schema identifiers to represent an array type alias (à la arktype). This transformation converts the schema into `t.Array(t.Ref(MySchema))`.
- Prefilled `$id` Field: Automatically prefilled the `$id` field to allow seamless referencing within the API documentation.
Here's an example 
```ts
const app = new Elysia()
.model({
number: t.Number()
})
.post('/', ({ body }) => body, {
response: 'number[]',
body: 'number[]',
})
``` 
Feel free to suggest or make any modifications as needed!

feat(DX): shortcut to Array Schema Validator

---

src/dynamic-handle.ts
src/index.ts
test/core/context.test.ts

It looks like the `route` context is returning `undefined` if the `aot=false`.
This commit try to fix it by passing the `route` to `createDynamicHandler`
Fix: [#898](https://github.com/elysiajs/elysia/issues/898)
---
Also added some test cases for it.

fix: undefined `route` context on `aot=false`

---

.github/workflows/ci.yml

Using the same strategy as Vite, this PR will publish a preview version of package that can be used to test the package without needing to publish manually by using [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new)
Noted that before pkg-pr-new bot can publish, and comment version to GitHub app needed to be installed first. ([As described in Setup step](https://github.com/stackblitz-labs/pkg.pr.new))
As a result, when testing with project locally from someone else PR's we can do something like this in `package.json`
```json
"dependencies": {
"elysia": "npm:https://pkg.pr.new/elysiajs/elysia@1181"
}
```

ci: publish preview version of Elysia for testing on pull request

---

src/adapter/web-standard/handler.ts
test/adapter/web-standard/map-compact-response.test.ts
test/adapter/web-standard/map-early-response.test.ts
test/adapter/web-standard/map-response.test.ts
test/path/path.test.ts

```ts
it('return web api\'s File', async () => {
const app = new Elysia().get('/', () => new File(['Hello'], 'hello.txt', { type: 'text/plain' }))
const res = await app.handle(req('/'))
expect(res.headers.get('content-type')).toBe('text/plain;charset=utf-8')
expect(await res.text()).toBe('Hello')
expect(res.status).toBe(200)
expect(res.headers.get('accept-ranges')).toBe('bytes')
expect(res.headers.get('content-range')).toBe('bytes 0-4/5')
})
```

add support to return web API's File from handler

---

src/adapter/bun/index.ts
src/index.ts
src/ws/types.ts
test/ws/message.test.ts

fix: Websocket `beforeLoad` not being executed

---

src/adapter/bun/compose.ts
test/adapter/bun/index.test.ts

fixes #1238 
`src/adapter/bun/compose.ts` didn't account for routes that have a guard that requires query, thus leading to a bug. This PR adds a straightforward check for it, bypassing `sucrose` calls
While this works, I think(?) that it would be better to handle route validators (including standalone validators) inside `sucrose` if I understand the purpose of this function right, but as of now I can't think of a way to do it properly
Would love to hear SaltyAoms thought on it. Also there is a test included for this specific case

fix(#1238): bun adapter add qi to routes that need query from guard

---

src/adapter/bun/index.ts
test/ws/message.test.ts

This PR fixes a few issues related to catching websocket errors.
To reproduce, run `bun run example/websocket.ts` with the following code (an uncaught error occurs):
```typescript
import { Elysia } from "../src";
const app = new Elysia()
.state("start", "here")
.ws("/ws", {
open(ws) {
throw new Error("asdf");
ws.subscribe("asdf");
console.log("Open Connection:", ws.id);
},
close(ws) {
console.log("Closed Connection:", ws.id);
},
message(ws, message) {
ws.publish("asdf", message);
ws.send("asdf", message);
},
})
.get("/publish/:publish", ({ params: { publish: text } }) => {
app.server!.publish("asdf", text);
return text;
})
.listen(3000, (server) => {
console.log(`http://${server.hostname}:${server.port}`);
});
const ws = new WebSocket('ws://localhost:3000/ws')
ws.onopen = () => { …
```

fix: websocket errors not catching

---

test/validator/params.test.ts

The Bun team is considering disallowing nested `it`/`test` blocks. Currently, tests run with canary builds of Bun will fail if nested `it` statements are found, but we may revert this change.
If we decide to move forward with it, this PR keeps your tests running. We run eslysia's tests in our CI, so this change also unblocks PRs on our end.

test: use `describe` instead of nested `it`

---

src/adapter/bun/compose.ts

This fixes an issue where `onRequest` handlers would not fire, breaking plugins such as `@elysiajs/cors`.
I believe this was caused by not including `createOnRequestHandler()` in the compose phase, even if some `request` handlers should be registered.
Fixes #1308

fix: onRequest not firing

---

src/adapter/bun/handler-native.ts
src/adapter/bun/index.ts

This PR aims to fix the issue with serving imported HTML as described in: https://github.com/elysiajs/elysia/issues/1297
I am not sure if this is the best way to solve that problem, I've noticed that when we run app in dev then the import returns HTMLBundle instance, in compiled apps(built with `--compile`) we are getting plain object. Based on https://github.com/oven-sh/bun/blob/fa1ad5425730c2f8d0c6046d6d49bb635e5d7383/packages/bun-types/bun.d.ts#L6086 HTMLBundle interface I changed the way how we check if given object is a bundle. 
I don't know how to emulate `--compile` in the tests  so there is no test for that particular scenario, I've tested it manually. If anyone knows how to do that I would appreciate guidance/tips how to write such test.

Fix HTML imported pages in compiled apps

---

src/types.ts
test/types/index.ts

This PR should fix type inference when Elysia instance uses array of plugins with prefix, it also should infer same route type as single plugin usage
Type tests are available in https://github.com/miello/elysia/blob/53678c8083b5c7b3f24896440347b07f5698af86/test/types/index.ts#L962
----

fix: array of plugin usage causes incorrect path aggregation

---

CHANGELOG.md
example/a.ts
package.json
src/adapter/bun/index.ts
src/adapter/cloudflare-worker/index.ts
src/adapter/types.ts
src/adapter/web-standard/index.ts
src/index.ts
src/universal/file.ts
test/adapter/bun/index.test.ts

Feature:
- experimental `adapter/cloudflare-worker`
- add `ElysiaAdapter.beforeCompile`
Change:
- do not prettify routes when using `guard`, `group`
- use `process.getBuiltinModule` instead of dynamic import for file
- `Elysia.file.value` on Web Standard Adapter now is not a promise

1.4.7 patch

---

CHANGELOG.md
bun.lock
example/a.ts
package.json
src/adapter/bun/handler.ts
src/adapter/web-standard/handler.ts
src/compose.ts
src/sucrose.ts

Improvement:
- automatically clear up sucrose cache when not used
- remove `Bun.hash` from checksum calculation
Change:
- make `file-type` optional to reduce bundle size
- [#1432](https://github.com/elysiajs/elysia/pull/1432) missing context (set) in mapResponse for ElysiaFile
- [#1435](https://github.com/elysiajs/elysia/pull/1435) missing cookies in SSE

1.4.8 patch
