elysiajs/elysia

package.json
test/node/.gitignore
test/node/cjs/index.js
test/node/cjs/package.json
test/node/esm/index.js
test/node/esm/package.json

- Fixed `exports` in `package.json` as mentioned in https://github.com/elysiajs/elysia/issues/50
- Added tests for `CJS` & `ESM` under `Node.js`

🔧fix: `exports` in `package.json`

---

src/index.ts

https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/

use node:process for cloudflare workers

---

README.md

Small improvement in grammar, feel free to correct me (I am not a native speaker nor I am an expert). You could argue that both are correct since known can be used as noun and verb, but in this case "former" sounds unusual. Reject this PR if maintainers find grammar ok.

docs: slight grammar adjustment

---

src/compose.ts
test/after-handle.test.ts

Closes https://github.com/elysiajs/elysia/issues/166

fix: `mapEarlyResponse` with `aot` on after handle

---

example/websocket.ts
src/ws/index.ts
test/ws/connection.test.ts
test/ws/message.test.ts
test/ws/utils.ts

Hi 👋
i noticed you checked off everything except tests for WebSocket in https://github.com/elysiajs/elysia/pull/103.
- added unit tests
- fixed example & api method
There was a bug in `isSubscribed` which lead to `Expected 'this' to be instanceof ServerWebSocket`:
https://github.com/elysiajs/elysia/blob/104e22d181423a4422f366d98d8f7841a21a70b8/src/ws/index.ts#L92-L94

WebSocket - added unit tests and fixed example & api

---

CONTRIBUTING.md

doc: fix typo in CONTRIBUTING.md

---

.github/dependabot.yml
.github/workflows/ci.yml

Same as https://github.com/elysiajs/elysia-html/pull/19
https://github.com/arthurfiorette/elysia/actions

Add github action to run bun test

---

src/error.ts
test/error.test.ts

Closes https://github.com/elysiajs/elysia/issues/186

🔧 fix: `InternalServerError` code

---

src/ws/index.ts
test/ws/destructuring.test.ts

Closes https://github.com/elysiajs/elysia/issues/195
But idk if it's worth it, as someone mentioned here:: https://github.com/elysiajs/elysia/issues/195#issuecomment-1728545341

fix: allow WebSocket destructuring

---

package.json

The upgrade is for this fix.
Tests are related to typebox and wouldn't be needed here.
Although, this is minor version would require a reinstall to fix this, so an upgrade would be any easy one.
https://github.com/sinclairzx81/typebox/pull/608

upgrade typebox's minor version

---

src/type-system.ts

I Add font/otf , font/ttf , font/woff and font/woff2

add font/* to SchemaOptions

---

src/ws/index.ts

Removes crypto api reference in favor of web crypto.
Should fix
- issues outlined in this thread: https://discord.com/channels/1044804142461362206/1194817027811053629
- (vite failing when it tries to bundle elysia)
- cloudflare worker support

Remove crypto in favor of webcrypto

---

src/type-system.ts
test/type-system/booleanString.test.ts
test/validator/query.test.ts

Closes https://github.com/elysiajs/elysia/issues/436

feat: BooleanString

---

src/index.ts

All tests passed
This PR fixes #463

Handle spread operator use on possible null or undefined in index.ts

---

.gitignore
tsconfig.test.json

Type check 3x faster
no cache:
with cache:

chore: cache tsc buildinfo for running faster

---

src/type-system.ts
test/types/type-system.ts

Closes https://github.com/elysiajs/elysia/issues/809

fix: ArrayString type

---

src/context.ts
src/dynamic-handle.ts
test/core/dynamic.test.ts

This PR fixes https://github.com/elysiajs/elysia/issues/946

🔧 fix array parser on query string when AOT is off

---

src/dynamic-handle.ts
test/core/dynamic.test.ts

This PR fixes https://github.com/elysiajs/elysia/issues/959

🔧 fix literal handler when AOT is off

---

src/dynamic-handle.ts
test/core/dynamic.test.ts
test/core/elysia.test.ts

This PR fixes https://github.com/elysiajs/elysia/issues/950
I could not fix the default value for cookies but, as far as I checked, it already doesn't work when AOT is on, so I think that this PR is good enough for now. At least it ensures that the behavior when AOT is on or off is even.

🔧 fix schema default value when AOT is off

---

src/dynamic-handle.ts
test/lifecycle/error.test.ts

Fixes https://github.com/elysiajs/elysia/issues/974

fix: error responses with aot: false

---

src/index.ts
test/plugins/plugin.test.ts

Fixes https://github.com/elysiajs/elysia/issues/945

fix: await nested async plugins

---

src/compose.ts
test/validator/body.test.ts

Issue: #1003
idk maybe this check is a bad idea, but all tests passed

fix: invalid parsing body with missed fields if used object model
